source "https://rubygems.org"
ruby File.read("#{__dir__}/.ruby-version")

gemspec

# gem "foobara-dotenv-loader"
# gem "foobara-dotenv-loader", path: "../dotenv-loader"
# gem "foobara-redis-crud-driver"
# gem "foobara-redis-crud-driver", path: "..-connector", branch: "main"
# gem "foobara-redis-crud-driver"
# gem "foobara-redis-crud-driver", path: "../redis-crud-driver"
# gem "foobara-redis-crud-driver"
# gem "foobara-redis-crud-driver", path: "../redis-crud-driver"
# gem "foobara-redis-crud-driver"
# gem "foobara-redis-crud-driver", path: "../redis-crud-driver"
# gem "foobara-redis-crud-driver"
# gem "foobara-sh-cli-connector", path: "../sh-cli-connector"
# gem "foobara-util", path: "../util"

gem "rake"

group :development do
  gem "foob"
  gem "foobara-rubocop-rules", "~> 0.0.1"
  gem "guard-rspec"
  gem "rubocop-rake"
  gem "rubocop-rspec"
end

group :development, :test do
  gem "pry"
  gem "pry-byebug"
end

group :test do
  gem "foobara-spec-helpers", "~> 0.0.1"
  gem "rspec"
  gem "rspec-its"
  gem "simplecov"
end
